# Generated by Django 4.2.1 on 2023-12-25 08:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_alter_term_content"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pricelist",
            name="menu",
        ),
    ]
